ALTER TABLE "fare_configs" ADD COLUMN IF NOT EXISTS "surge_multiplier" DECIMAL(4, 2) NOT NULL DEFAULT 1;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "surge_multiplier" DECIMAL(4, 2) NOT NULL DEFAULT 1;
