import type { AdminRole } from '@prisma/client';

export const PERMISSION_KEYS = {
  MANAGE_USERS: 'manage_users',
  MANAGE_DRIVERS: 'manage_drivers',
  MANAGE_FLEETS: 'manage_fleets',
  MANAGE_ROLES: 'manage_roles',
  VIEW_REPORTS: 'view_reports',
  MANAGE_DOCUMENTS: 'manage_documents',
  MANAGE_PENALTIES: 'manage_penalties',
  MANAGE_NOTES: 'manage_notes',
  VIEW_FINANCE: 'view_finance',
  MANAGE_WALLET_ADJUSTMENTS: 'manage_wallet_adjustments',
  APPROVE_WALLET_ADJUSTMENTS: 'approve_wallet_adjustments',
  MANAGE_PAYOUTS: 'manage_payouts',
  EXPORT_FINANCE_REPORTS: 'export_finance_reports',

  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_UPDATE: 'ADMIN_UPDATE',
  ADMIN_SUSPEND: 'ADMIN_SUSPEND',

  DRIVER_VIEW: 'DRIVER_VIEW',
  DRIVER_DOCUMENT_VIEW: 'DRIVER_DOCUMENT_VIEW',
  DRIVER_APPROVE: 'DRIVER_APPROVE',
  DRIVER_REJECT: 'DRIVER_REJECT',
  DRIVER_SUSPEND: 'DRIVER_SUSPEND',

  PASSENGER_VIEW: 'PASSENGER_VIEW',
  PASSENGER_SUSPEND: 'PASSENGER_SUSPEND',

  FLEET_VIEW: 'FLEET_VIEW',
  FLEET_CREATE: 'FLEET_CREATE',
  FLEET_UPDATE: 'FLEET_UPDATE',
  FLEET_SUSPEND: 'FLEET_SUSPEND',

  FINANCE_VIEW: 'FINANCE_VIEW',
  WALLET_VIEW: 'WALLET_VIEW',
  PAYOUT_VIEW: 'PAYOUT_VIEW',
  PAYOUT_APPROVE: 'PAYOUT_APPROVE',
  FINANCE_REPORT_VIEW: 'FINANCE_REPORT_VIEW',

  TICKET_VIEW: 'TICKET_VIEW',
  TICKET_ASSIGN: 'TICKET_ASSIGN',
  TICKET_RESPOND: 'TICKET_RESPOND',
  TICKET_ESCALATE: 'TICKET_ESCALATE',
  TICKET_RESOLVE: 'TICKET_RESOLVE',

  COUNTRY_VIEW: 'COUNTRY_VIEW',
  COUNTRY_CREATE: 'COUNTRY_CREATE',
  CITY_VIEW: 'CITY_VIEW',
  CITY_CREATE: 'CITY_CREATE',
  CONTINENT_VIEW: 'CONTINENT_VIEW',
  CONTINENT_CREATE: 'CONTINENT_CREATE',
  REGIONAL_VIEW: 'REGIONAL_VIEW',
  REGIONAL_CREATE: 'REGIONAL_CREATE',

  FARE_MANAGE: 'FARE_MANAGE',
} as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS];

export const DEFAULT_PERMISSIONS: { key: PermissionKey; meaning: string }[] = [
  { key: PERMISSION_KEYS.MANAGE_USERS, meaning: 'List, view, update user status' },
  { key: PERMISSION_KEYS.MANAGE_DRIVERS, meaning: 'Approve/reject drivers' },
  { key: PERMISSION_KEYS.MANAGE_FLEETS, meaning: 'Fleet companies & drivers' },
  { key: PERMISSION_KEYS.MANAGE_ROLES, meaning: 'Create/edit roles and assign permissions' },
  { key: PERMISSION_KEYS.VIEW_REPORTS, meaning: 'Read-only reports/audit' },
  { key: PERMISSION_KEYS.MANAGE_DOCUMENTS, meaning: 'Review KYC documents' },
  { key: PERMISSION_KEYS.MANAGE_PENALTIES, meaning: 'Apply wallet penalties' },
  { key: PERMISSION_KEYS.MANAGE_NOTES, meaning: 'Add support notes' },
  { key: PERMISSION_KEYS.VIEW_FINANCE, meaning: 'View wallets, transactions, and finance dashboard' },
  { key: PERMISSION_KEYS.MANAGE_WALLET_ADJUSTMENTS, meaning: 'Request manual wallet credits and debits' },
  { key: PERMISSION_KEYS.APPROVE_WALLET_ADJUSTMENTS, meaning: 'Approve or reject wallet adjustments and payouts' },
  { key: PERMISSION_KEYS.MANAGE_PAYOUTS, meaning: 'Create payout requests' },
  { key: PERMISSION_KEYS.EXPORT_FINANCE_REPORTS, meaning: 'Export finance reports' },

  { key: PERMISSION_KEYS.ADMIN_VIEW, meaning: 'View administrators in your scope' },
  { key: PERMISSION_KEYS.ADMIN_CREATE, meaning: 'Create administrators you are allowed to invite' },
  { key: PERMISSION_KEYS.ADMIN_UPDATE, meaning: 'Update administrators in your scope' },
  { key: PERMISSION_KEYS.ADMIN_SUSPEND, meaning: 'Suspend administrators in your scope' },

  { key: PERMISSION_KEYS.DRIVER_VIEW, meaning: 'View drivers in your assigned scope' },
  { key: PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW, meaning: 'View driver verification documents' },
  { key: PERMISSION_KEYS.DRIVER_APPROVE, meaning: 'Approve driver documents / onboarding' },
  { key: PERMISSION_KEYS.DRIVER_REJECT, meaning: 'Reject driver documents / onboarding' },
  { key: PERMISSION_KEYS.DRIVER_SUSPEND, meaning: 'Suspend drivers in your scope' },

  { key: PERMISSION_KEYS.PASSENGER_VIEW, meaning: 'View passengers in your assigned scope' },
  { key: PERMISSION_KEYS.PASSENGER_SUSPEND, meaning: 'Suspend passengers in your scope' },

  { key: PERMISSION_KEYS.FLEET_VIEW, meaning: 'View fleets in your assigned scope' },
  { key: PERMISSION_KEYS.FLEET_CREATE, meaning: 'Create fleet companies' },
  { key: PERMISSION_KEYS.FLEET_UPDATE, meaning: 'Update fleet profile and settings' },
  { key: PERMISSION_KEYS.FLEET_SUSPEND, meaning: 'Suspend fleets in your scope' },

  { key: PERMISSION_KEYS.FINANCE_VIEW, meaning: 'View finance dashboards in your scope' },
  { key: PERMISSION_KEYS.WALLET_VIEW, meaning: 'View wallets in your scope' },
  { key: PERMISSION_KEYS.PAYOUT_VIEW, meaning: 'View payout requests' },
  { key: PERMISSION_KEYS.PAYOUT_APPROVE, meaning: 'Approve payouts and settlements' },
  { key: PERMISSION_KEYS.FINANCE_REPORT_VIEW, meaning: 'View finance reports' },

  { key: PERMISSION_KEYS.TICKET_VIEW, meaning: 'View support tickets / notes' },
  { key: PERMISSION_KEYS.TICKET_ASSIGN, meaning: 'Assign support tickets' },
  { key: PERMISSION_KEYS.TICKET_RESPOND, meaning: 'Respond to support tickets' },
  { key: PERMISSION_KEYS.TICKET_ESCALATE, meaning: 'Escalate support tickets' },
  { key: PERMISSION_KEYS.TICKET_RESOLVE, meaning: 'Resolve support tickets' },

  { key: PERMISSION_KEYS.COUNTRY_VIEW, meaning: 'View countries (regions)' },
  { key: PERMISSION_KEYS.COUNTRY_CREATE, meaning: 'Create countries (regions)' },
  { key: PERMISSION_KEYS.CITY_VIEW, meaning: 'View cities (fleet regions)' },
  { key: PERMISSION_KEYS.CITY_CREATE, meaning: 'Create cities (fleet regions)' },
  { key: PERMISSION_KEYS.CONTINENT_VIEW, meaning: 'View continents' },
  { key: PERMISSION_KEYS.CONTINENT_CREATE, meaning: 'Create continents' },
  { key: PERMISSION_KEYS.REGIONAL_VIEW, meaning: 'View provinces / regional subdivisions' },
  { key: PERMISSION_KEYS.REGIONAL_CREATE, meaning: 'Create provinces / regional subdivisions' },

  { key: PERMISSION_KEYS.FARE_MANAGE, meaning: 'Add, edit, and delete city / country fare configs' },
];

/** New scoped keys also satisfy existing requirePermission(legacy) checks. */
export const NEW_TO_LEGACY: Partial<Record<PermissionKey, PermissionKey[]>> = {
  [PERMISSION_KEYS.ADMIN_VIEW]: [PERMISSION_KEYS.MANAGE_USERS],
  [PERMISSION_KEYS.ADMIN_CREATE]: [PERMISSION_KEYS.MANAGE_USERS],
  [PERMISSION_KEYS.ADMIN_UPDATE]: [PERMISSION_KEYS.MANAGE_USERS],
  [PERMISSION_KEYS.ADMIN_SUSPEND]: [PERMISSION_KEYS.MANAGE_USERS, PERMISSION_KEYS.MANAGE_PENALTIES],
  [PERMISSION_KEYS.DRIVER_VIEW]: [PERMISSION_KEYS.MANAGE_DRIVERS],
  [PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW]: [PERMISSION_KEYS.MANAGE_DOCUMENTS],
  [PERMISSION_KEYS.DRIVER_APPROVE]: [PERMISSION_KEYS.MANAGE_DRIVERS, PERMISSION_KEYS.MANAGE_DOCUMENTS],
  [PERMISSION_KEYS.DRIVER_REJECT]: [PERMISSION_KEYS.MANAGE_DRIVERS, PERMISSION_KEYS.MANAGE_DOCUMENTS],
  [PERMISSION_KEYS.DRIVER_SUSPEND]: [PERMISSION_KEYS.MANAGE_DRIVERS],
  [PERMISSION_KEYS.PASSENGER_VIEW]: [PERMISSION_KEYS.MANAGE_USERS],
  [PERMISSION_KEYS.PASSENGER_SUSPEND]: [PERMISSION_KEYS.MANAGE_USERS],
  [PERMISSION_KEYS.FLEET_VIEW]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.FLEET_CREATE]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.FLEET_UPDATE]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.FLEET_SUSPEND]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.FINANCE_VIEW]: [PERMISSION_KEYS.VIEW_FINANCE],
  [PERMISSION_KEYS.WALLET_VIEW]: [PERMISSION_KEYS.VIEW_FINANCE],
  [PERMISSION_KEYS.PAYOUT_VIEW]: [PERMISSION_KEYS.VIEW_FINANCE, PERMISSION_KEYS.MANAGE_PAYOUTS],
  [PERMISSION_KEYS.PAYOUT_APPROVE]: [PERMISSION_KEYS.APPROVE_WALLET_ADJUSTMENTS],
  [PERMISSION_KEYS.FINANCE_REPORT_VIEW]: [PERMISSION_KEYS.EXPORT_FINANCE_REPORTS, PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.TICKET_VIEW]: [PERMISSION_KEYS.MANAGE_NOTES, PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.TICKET_ASSIGN]: [PERMISSION_KEYS.MANAGE_NOTES],
  [PERMISSION_KEYS.TICKET_RESPOND]: [PERMISSION_KEYS.MANAGE_NOTES],
  [PERMISSION_KEYS.TICKET_ESCALATE]: [PERMISSION_KEYS.MANAGE_NOTES],
  [PERMISSION_KEYS.TICKET_RESOLVE]: [PERMISSION_KEYS.MANAGE_NOTES],
  [PERMISSION_KEYS.COUNTRY_VIEW]: [PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.CITY_VIEW]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.CITY_CREATE]: [PERMISSION_KEYS.MANAGE_FLEETS],
  [PERMISSION_KEYS.CONTINENT_VIEW]: [PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.CONTINENT_CREATE]: [PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.REGIONAL_VIEW]: [PERMISSION_KEYS.VIEW_REPORTS],
  [PERMISSION_KEYS.REGIONAL_CREATE]: [PERMISSION_KEYS.MANAGE_FLEETS],
};

/** Legacy keys imply the matching view-level scoped keys (not write keys). */
export const LEGACY_TO_NEW: Partial<Record<PermissionKey, PermissionKey[]>> = {
  [PERMISSION_KEYS.MANAGE_USERS]: [PERMISSION_KEYS.ADMIN_VIEW, PERMISSION_KEYS.PASSENGER_VIEW],
  [PERMISSION_KEYS.MANAGE_DRIVERS]: [PERMISSION_KEYS.DRIVER_VIEW],
  [PERMISSION_KEYS.MANAGE_FLEETS]: [PERMISSION_KEYS.FLEET_VIEW],
  [PERMISSION_KEYS.MANAGE_DOCUMENTS]: [PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW],
  [PERMISSION_KEYS.VIEW_FINANCE]: [PERMISSION_KEYS.FINANCE_VIEW, PERMISSION_KEYS.WALLET_VIEW],
  [PERMISSION_KEYS.MANAGE_PAYOUTS]: [PERMISSION_KEYS.PAYOUT_VIEW],
  [PERMISSION_KEYS.APPROVE_WALLET_ADJUSTMENTS]: [PERMISSION_KEYS.PAYOUT_APPROVE],
  [PERMISSION_KEYS.EXPORT_FINANCE_REPORTS]: [PERMISSION_KEYS.FINANCE_REPORT_VIEW],
  [PERMISSION_KEYS.MANAGE_NOTES]: [PERMISSION_KEYS.TICKET_VIEW],
  [PERMISSION_KEYS.VIEW_REPORTS]: [PERMISSION_KEYS.TICKET_VIEW],
};

export function expandPermissionAliases(keys: Iterable<string>): string[] {
  const set = new Set<string>(keys);
  for (const key of [...set]) {
    const asNew = NEW_TO_LEGACY[key as PermissionKey];
    if (asNew) asNew.forEach((k) => set.add(k));
    const asLegacy = LEGACY_TO_NEW[key as PermissionKey];
    if (asLegacy) asLegacy.forEach((k) => set.add(k));
  }
  return [...set];
}

const GEO_ADMIN_DEFAULTS: PermissionKey[] = [
  PERMISSION_KEYS.ADMIN_VIEW,
  PERMISSION_KEYS.ADMIN_CREATE,
  PERMISSION_KEYS.ADMIN_UPDATE,
  PERMISSION_KEYS.DRIVER_VIEW,
  PERMISSION_KEYS.FLEET_VIEW,
  PERMISSION_KEYS.PASSENGER_VIEW,
  PERMISSION_KEYS.TICKET_VIEW,
  PERMISSION_KEYS.FINANCE_VIEW,
  PERMISSION_KEYS.CONTINENT_VIEW,
  PERMISSION_KEYS.COUNTRY_VIEW,
  PERMISSION_KEYS.REGIONAL_VIEW,
  PERMISSION_KEYS.CITY_VIEW,
  PERMISSION_KEYS.FARE_MANAGE,
];

export const ADMIN_ROLE_DEFAULTS: Record<Exclude<AdminRole, 'SUPER_ADMIN'>, PermissionKey[]> = {
  SUB_ADMIN: [
    PERMISSION_KEYS.ADMIN_VIEW,
    PERMISSION_KEYS.DRIVER_VIEW,
    PERMISSION_KEYS.FLEET_VIEW,
    PERMISSION_KEYS.PASSENGER_VIEW,
    PERMISSION_KEYS.TICKET_VIEW,
  ],
  FINANCE_USER: [
    PERMISSION_KEYS.FINANCE_VIEW,
    PERMISSION_KEYS.WALLET_VIEW,
    PERMISSION_KEYS.PAYOUT_VIEW,
    PERMISSION_KEYS.PAYOUT_APPROVE,
    PERMISSION_KEYS.FINANCE_REPORT_VIEW,
  ],
  PLATFORM_SUPPORT: [
    PERMISSION_KEYS.TICKET_VIEW,
    PERMISSION_KEYS.TICKET_ASSIGN,
    PERMISSION_KEYS.TICKET_RESPOND,
    PERMISSION_KEYS.TICKET_ESCALATE,
    PERMISSION_KEYS.TICKET_RESOLVE,
  ],
  GLOBAL_ADMIN: [
    ...GEO_ADMIN_DEFAULTS,
    PERMISSION_KEYS.CONTINENT_CREATE,
    PERMISSION_KEYS.COUNTRY_CREATE,
    PERMISSION_KEYS.FINANCE_REPORT_VIEW,
  ],
  CONTINENT_ADMIN: [
    ...GEO_ADMIN_DEFAULTS,
    PERMISSION_KEYS.COUNTRY_CREATE,
  ],
  COUNTRY_ADMIN: [
    ...GEO_ADMIN_DEFAULTS,
    PERMISSION_KEYS.REGIONAL_CREATE,
    PERMISSION_KEYS.CITY_CREATE,
    PERMISSION_KEYS.FLEET_CREATE,
  ],
  REGIONAL_ADMIN: [
    ...GEO_ADMIN_DEFAULTS,
    PERMISSION_KEYS.CITY_CREATE,
    PERMISSION_KEYS.DRIVER_SUSPEND,
  ],
  CITY_ADMIN: [
    PERMISSION_KEYS.ADMIN_VIEW,
    PERMISSION_KEYS.ADMIN_CREATE,
    PERMISSION_KEYS.ADMIN_UPDATE,
    PERMISSION_KEYS.DRIVER_VIEW,
    PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW,
    PERMISSION_KEYS.FLEET_VIEW,
    PERMISSION_KEYS.PASSENGER_VIEW,
    PERMISSION_KEYS.TICKET_VIEW,
    PERMISSION_KEYS.TICKET_ASSIGN,
    PERMISSION_KEYS.TICKET_RESPOND,
    PERMISSION_KEYS.CITY_VIEW,
    PERMISSION_KEYS.FARE_MANAGE,
  ],
  FLEET_OWNER: [
    PERMISSION_KEYS.DRIVER_VIEW,
    PERMISSION_KEYS.FLEET_VIEW,
    PERMISSION_KEYS.FLEET_UPDATE,
    PERMISSION_KEYS.FINANCE_VIEW,
    PERMISSION_KEYS.ADMIN_CREATE,
    PERMISSION_KEYS.ADMIN_UPDATE,
    PERMISSION_KEYS.ADMIN_VIEW,
    PERMISSION_KEYS.CITY_VIEW,
    PERMISSION_KEYS.CITY_CREATE,
  ],
  REGIONAL_FLEET: [
    PERMISSION_KEYS.DRIVER_VIEW,
    PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW,
    PERMISSION_KEYS.DRIVER_APPROVE,
    PERMISSION_KEYS.DRIVER_REJECT,
    PERMISSION_KEYS.ADMIN_CREATE,
    PERMISSION_KEYS.ADMIN_VIEW,
    PERMISSION_KEYS.TICKET_VIEW,
    PERMISSION_KEYS.TICKET_ASSIGN,
    PERMISSION_KEYS.TICKET_ESCALATE,
    PERMISSION_KEYS.CITY_VIEW,
  ],
  FLEET_SUPPORT: [
    PERMISSION_KEYS.TICKET_VIEW,
    PERMISSION_KEYS.TICKET_RESPOND,
    PERMISSION_KEYS.TICKET_RESOLVE,
    PERMISSION_KEYS.DRIVER_VIEW,
  ],
  FLEET_FINANCE: [
    PERMISSION_KEYS.FINANCE_VIEW,
    PERMISSION_KEYS.WALLET_VIEW,
    PERMISSION_KEYS.PAYOUT_VIEW,
    PERMISSION_KEYS.FINANCE_REPORT_VIEW,
    PERMISSION_KEYS.DRIVER_VIEW,
  ],
};

export const ALLOWED_INVITES: Record<AdminRole, AdminRole[]> = {
  SUPER_ADMIN: [
    'GLOBAL_ADMIN',
    'SUB_ADMIN',
    'FINANCE_USER',
    'PLATFORM_SUPPORT',
    'CONTINENT_ADMIN',
    'COUNTRY_ADMIN',
    'FLEET_OWNER',
  ],
  GLOBAL_ADMIN: ['CONTINENT_ADMIN'],
  CONTINENT_ADMIN: ['COUNTRY_ADMIN'],
  COUNTRY_ADMIN: ['REGIONAL_ADMIN'],
  REGIONAL_ADMIN: ['CITY_ADMIN'],
  CITY_ADMIN: ['FLEET_OWNER'],
  SUB_ADMIN: [],
  FINANCE_USER: [],
  PLATFORM_SUPPORT: [],
  FLEET_OWNER: ['REGIONAL_FLEET', 'FLEET_FINANCE', 'FLEET_SUPPORT'],
  REGIONAL_FLEET: ['FLEET_SUPPORT'],
  FLEET_SUPPORT: [],
  FLEET_FINANCE: [],
};

export const DEFAULT_ROLE_TEMPLATES = [
  {
    name: 'Support Agent',
    slug: 'support-agent',
    description: 'Basic user support access',
    permissionKeys: [
      PERMISSION_KEYS.MANAGE_USERS,
      PERMISSION_KEYS.MANAGE_NOTES,
      PERMISSION_KEYS.VIEW_REPORTS,
      PERMISSION_KEYS.TICKET_VIEW,
      PERMISSION_KEYS.TICKET_RESPOND,
      PERMISSION_KEYS.TICKET_RESOLVE,
    ],
    isSystem: true,
  },
  {
    name: 'Fleet Manager',
    slug: 'fleet-manager',
    description: 'Manage fleet operations',
    permissionKeys: [
      PERMISSION_KEYS.MANAGE_FLEETS,
      PERMISSION_KEYS.MANAGE_DRIVERS,
      PERMISSION_KEYS.VIEW_REPORTS,
      PERMISSION_KEYS.DRIVER_VIEW,
      PERMISSION_KEYS.DRIVER_DOCUMENT_VIEW,
      PERMISSION_KEYS.DRIVER_APPROVE,
      PERMISSION_KEYS.DRIVER_REJECT,
    ],
    isSystem: true,
  },
  {
    name: 'Sub Admin',
    slug: 'sub-admin',
    description: 'Operations sub-admin without role management',
    permissionKeys: [
      PERMISSION_KEYS.MANAGE_USERS,
      PERMISSION_KEYS.MANAGE_DRIVERS,
      PERMISSION_KEYS.MANAGE_DOCUMENTS,
      PERMISSION_KEYS.MANAGE_NOTES,
      PERMISSION_KEYS.VIEW_REPORTS,
      PERMISSION_KEYS.ADMIN_VIEW,
      PERMISSION_KEYS.DRIVER_VIEW,
      PERMISSION_KEYS.FLEET_VIEW,
      PERMISSION_KEYS.PASSENGER_VIEW,
      PERMISSION_KEYS.TICKET_VIEW,
    ],
    isSystem: true,
  },
  {
    name: 'Finance Officer',
    slug: 'finance-officer',
    description: 'Platform finance and wallet operations',
    permissionKeys: [
      PERMISSION_KEYS.VIEW_FINANCE,
      PERMISSION_KEYS.MANAGE_WALLET_ADJUSTMENTS,
      PERMISSION_KEYS.MANAGE_PAYOUTS,
      PERMISSION_KEYS.EXPORT_FINANCE_REPORTS,
      PERMISSION_KEYS.VIEW_REPORTS,
      PERMISSION_KEYS.FINANCE_VIEW,
      PERMISSION_KEYS.WALLET_VIEW,
      PERMISSION_KEYS.PAYOUT_VIEW,
      PERMISSION_KEYS.PAYOUT_APPROVE,
      PERMISSION_KEYS.FINANCE_REPORT_VIEW,
    ],
    isSystem: true,
  },
] as const;
